name: Question/Help request
description: You have a question or you need help about the library
body:
  - type: markdown
    attributes:
      value: |
        Please use the [Discussion tab](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/discussions) or the [Gitter chat room](https://gitter.im/ButchersBoy/MaterialDesignInXamlToolkit) for this type of request.
        
        
        